spring:
  redis:
    host: redis-18324.c240.us-east-1-3.ec2.redns.redis-cloud.com
    port: 18324
    ssl: true
    password: MM2AWiSblFyq0Ts6mszifu30C2ixFTrg
  data:
    mongodb:
      uri: mongodb+srv://journaldb:Journal321@cluster0.mj9mk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true
server:
  port: 8081
  servlet:
    context-path: /journalapp

#add this file instead of application.properties file. But application.properties file is given more preference if its present
# ./mvnw clean package -D spring.profiles.active=dev command to set active profile to dev and create jar