spring:
  profiles:
    active: dev
    #change to dev or prod to specify active env in main app
  mail:
    host: smtp.gmail.com
    port: 587
    username: ashutosh98sharan@gmail.com
    password: vwla jszt muwu kehl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    net:
      journal:
        JournalApp: DEBUG #will print debug logs as well\


weather:
  api:
    key: 1ATJysW90wYgLLWJaRXoOBowUAAvD67Q
  location:
    key: 2146519 # this is Amherst